config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root to: redirect(path: "/users")

  resources :users do
    resource :billing_detail, only: [:show], controller: "users/billing_details"
    resources :occupations, only: %i[show new create edit update], controller: "users/occupations"
    resources :banks, only: %i[show new create edit update], controller: "users/banks"
    resources :addresses, only: %i[show new create edit update], controller: "users/addresses"

    collection do
      resources :bulk_trashes, only: %i[create], controller: "users/bulk_trashes", as: "user_bulk_trashes"
    end
  end
end

app/models/concerns/user/dummy_jsonable.rb
# frozen_string_literal: true

class User
  module DummyJsonable
    extend ActiveSupport::Concern

    included do
      has_one :dummy_json_user_response, dependent: :destroy
    end

    # rubocop:disable Metrics/BlockLength, Metrics/AbcSize, Metrics/MethodLength
    class_methods do
      def create_from_dummy_json_response!(dummy_json_user_response)
        return if dummy_json_user_response.user_id.present?

        data = process_dummy_json_data(dummy_json_user_response.data)
        user = nil
        transaction do
          user = create!(data)
          dummy_json_user_response.update_attribute(:user, user) # rubocop:disable Rails/SkipsModelValidations
        end

        user
      end

      def process_dummy_json_data(dummy_data)
        data = {
          bank_attributes: {},
          address_attributes: {},
          occupation_attributes: {}
        }
        underscored_data = dummy_data.except("id").deep_transform_keys { |key| key.underscore.to_sym }
        underscored_data.each_with_object(data) do |(key, value), processed_data|
          process_dummy_attribute(key, value, processed_data)
        end
      end

      def process_dummy_attribute(key, value, processed_data)
        case key
        when :hair
          processed_data[:hair_color] = value[:color]
          processed_data[:hair_type] = value[:type]
        when :blood_group
          # NOTE: DummyJson blood type field uses the minus character (codepoint 8722) which could be confusing
          processed_data[:blood_group] = value.gsub("−", "-")
        when :address
          coordinates = value[:coordinates]
          address_data = value.except(:coordinates)
          address_data[:latitude] = coordinates[:lat]
          address_data[:longitude] = coordinates[:lng]
          processed_data[:address_attributes] = address_data
        when :company
          coordinates = value[:address][:coordinates]
          occupation_data = value[:address].except(:coordinates)
          occupation_data[:latitude] = coordinates[:lat]
          occupation_data[:longitude] = coordinates[:lng]
          occupation_data[:company_name] = value[:name]
          occupation_data[:department] = value[:department]
          occupation_data[:title] = value[:title]
          processed_data[:occupation_attributes] = occupation_data
        when :bank
          card_expiration_month, card_expiration_year = value[:card_expire].split("/").map(&:to_i)
          bank_data = value.except(:card_expire)
          bank_data[:card_expiration_year] = card_expiration_year + 2000
          bank_data[:card_expiration_month] = card_expiration_month
          processed_data[:bank_attributes] = bank_data
        else
          processed_data[key] = value
        end
      end
    end
    # rubocop:enable Metrics/BlockLength, Metrics/AbcSize, Metrics/MethodLength
  end
end

app/models/concerns/user/trashable.rb
# frozen_string_literal: true

class User
  module Trashable
    extend ActiveSupport::Concern

    INCINERATION_DELAY = 30.minutes

    included do
      validate :should_be_trashed_before_incineration, on: :update, if: :incinerating?
      after_update_commit :incinerate_later, if: -> { trashed? && status_previously_changed? }
    end

    class_methods do
      def bulk_trash(selected_ids)
        users = where(id: selected_ids)
        result = transaction do
          users.each { |user| raise ActiveRecord::Rollback unless user.trash }
          true
        end
        result.present?
      end
    end

    def trash
      update(status: :trashed)
    end

    def incinerate!
      UserMailer.with(user: self).incinerated.deliver_now
      destroy!
    end

    private

    def should_be_trashed_before_incineration
      errors.add(:status, :was_not_trashed) unless status_was.to_sym == :trashed
    end

    def incinerate_later
      UserIncinerationJob.perform_in(INCINERATION_DELAY, id)
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Trashable
  include DummyJsonable
  include CachePurgeable
  include PgSearch::Model

  has_one :bank, dependent: :destroy
  has_one :address, dependent: :destroy
  has_one :occupation, dependent: :destroy
  accepts_nested_attributes_for :bank, :address, :occupation
  validates_associated :bank, on: :create
  validates_associated :address, on: :create
  validates_associated :occupation, on: :create

  encrypts :password

  enum status: { registered: "registered", trashed: "trashed", incinerating: "incinerating" }
  enum gender: { female: "female", male: "male" }
  enum blood_group: {
    "A+" => "positive_a",
    "B+" => "positive_b",
    "AB+" => "positive_ab",
    "O+" => "positive_zero",
    "A-" => "negative_a",
    "B-" => "negative_b",
    "AB-" => "negative_ab",
    "O-" => "negative_zero"
  }

  MIN_AGE = 1
  MAX_AGE = 125
  scope :by_age, lambda { |from: nil, to: nil|
    from = from.presence || MIN_AGE
    to = to.presence || MAX_AGE
    where(age: (from.to_i..to.to_i))
  }

  pg_search_scope :by_full_name_and_email,
                  against: %i[first_name last_name maiden_name email],
                  using: { tsearch: { prefix: true } }

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, numericality: { only_integer: true, in: (MIN_AGE..MAX_AGE), allow_nil: true }

  def name
    [first_name, last_name].join(" ")
  end
end

app/controllers/users/addresses_controller.rb
# frozen_string_literal: true

module Users
  class AddressesController < ApplicationController
    before_action :set_user
    before_action :set_address, only: %i[show edit update]

    def show; end

    def new
      if @user.address
        redirect_to user_address_path(@user, @user.address)
        return
      end

      @address = Address.new(user: @user)
    end

    def edit; end

    def create
      @address = Address.new(address_params.merge(user: @user))

      respond_to do |format|
        if @address.save
          format.html { redirect_to user_billing_detail_path(@user), notice: "Address was successfully created." }
          format.json { render :show, status: :created, location: user_address_path(@user, @address) }
          format.turbo_stream
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @address.errors, status: :unprocessable_entity }
          format.turbo_stream do
            render turbo_stream:
                     turbo_stream.replace(dom_id(@address), partial: "users/addresses/form",
                                                            locals: { address: @address }),
                   status: :unprocessable_entity
          end
        end
      end
    end

    def update
      respond_to do |format|
        if @address.update(address_params)
          format.html { redirect_to user_billing_detail_path(@user), notice: "Address was successfully updated." }
          format.turbo_stream do
            redirect_to user_address_path(@user, @address), notice: "Address was successfully updated."
          end
          format.json { render :show, status: :ok, location: user_address_path(@user, @address) }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @address.errors, status: :unprocessable_entity }
          format.turbo_stream do
            render turbo_stream:
                     turbo_stream.replace(dom_id(@address), partial: "users/addresses/form",
                                                            locals: { address: @address }),
                   status: :unprocessable_entity
          end
        end
      end
    end

    private

    def set_user
      @user = User.find(params[:user_id])
    end

    def set_address
      @address = @user.address
    end

    def address_params
      params.require(:address).permit(
        :address, :city, :latitude, :longitude, :postal_code, :state
      )
    end
  end
end

app/controllers/users/banks_controller.rb
# frozen_string_literal: true

module Users
  class BanksController < ApplicationController
    before_action :set_user
    before_action :set_bank, only: %i[show edit update]

    def show; end

    def new
      if @user.bank
        redirect_to user_bank_path(@user, @user.bank)
        return
      end

      @bank = Bank.new(user: @user)
    end

    def edit; end

    def create
      @bank = Bank.new(bank_params.merge(user: @user))

      respond_to do |format|
        if @bank.save
          format.html { redirect_to user_billing_detail_path(@user), notice: "Bank was successfully created." }
          format.json { render :show, status: :created, location: user_bank_path(@user, @bank) }
          format.turbo_stream
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @bank.errors, status: :unprocessable_entity }
          format.turbo_stream do
            render turbo_stream:
                     turbo_stream.replace(dom_id(@bank), partial: "users/banks/form", locals: { bank: @bank }),
                   status: :unprocessable_entity
          end
        end
      end
    end

    def update
      respond_to do |format|
        if @bank.update(bank_params)
          format.html { redirect_to user_billing_detail_path(@user), notice: "Bank was successfully updated." }
          format.json { render :show, status: :ok, location: user_bank_path(@user, @bank) }
          format.turbo_stream { redirect_to user_bank_path(@user, @bank), notice: "Bank was successfully updated." }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @bank.errors, status: :unprocessable_entity }
          format.turbo_stream do
            render turbo_stream:
                     turbo_stream.replace(dom_id(@bank), partial: "users/banks/form", locals: { bank: @bank }),
                   status: :unprocessable_entity
          end
        end
      end
    end

    private

    def set_user
      @user = User.find(params[:user_id])
    end

    def set_bank
      @bank = @user.bank
    end

    def bank_params
      params.require(:bank).permit(
        :iban, :currency, :card_type, :card_number, :card_expiration_year, :card_expiration_month
      )
    end
  end
end

app/controllers/users/billing_details_controller.rb
# frozen_string_literal: true

module Users
  class BillingDetailsController < ApplicationController
    before_action :set_user
    before_action :set_bank
    before_action :set_address

    def show; end

    private

    def set_user
      @user = User.find(params[:user_id])
    end

    def set_bank
      @bank = @user.bank
    end

    def set_address
      @address = @user.address
    end
  end
end

app/controllers/users/bulk_trashes_controller.rb
# frozen_string_literal: true

module Users
  class BulkTrashesController < ApplicationController
    def create
      @selected_ids = bulk_trash_params[:selected_ids]
      respond_to do |format|
        if User.bulk_trash(@selected_ids)
          format.html { redirect_to users_path, notice: "Users were successfully trashed." }
          format.turbo_stream
          format.json { head :no_content }
        else
          format.html { redirect_to users_path, alert: "Users could not be trashed." }
          format.turbo_stream { redirect_to users_path, alert: "Users could not be trashed." }
          format.json { head :unprocessable_entity }
        end
      end
    end

    private

    def bulk_trash_params
      params.permit(selected_ids: [])
    end
  end
end

app/controllers/users/occupations_controller.rb
# frozen_string_literal: true

module Users
  class OccupationsController < ApplicationController
    before_action :set_user
    before_action :set_occupation, only: %i[show edit update]

    def show; end

    def new
      if @user.occupation
        redirect_to user_occupation_path(@user, @user.occupation)
        return
      end

      @occupation = Occupation.new(user: @user)
    end

    def edit; end

    def create
      @occupation = Occupation.new(occupation_params.merge(user: @user))

      respond_to do |format|
        if @occupation.save
          format.html do
            redirect_to user_occupation_path(@user, @occupation), notice: "Occupation was successfully created."
          end
          format.json { render :show, status: :created, location: user_occupation_path(@user, @occupation) }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @occupation.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @occupation.update(occupation_params)
          format.html do
            redirect_to user_occupation_path(@user, @occupation), notice: "Occupation was successfully updated."
          end
          format.json { render :show, status: :ok, location: user_occupation_path(@user, @occupation) }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @occupation.errors, status: :unprocessable_entity }
        end
      end
    end

    private

    def set_user
      @user = User.find(params[:user_id])
    end

    def set_occupation
      @occupation = @user.occupation
    end

    def occupation_params
      params.require(:occupation).permit(
        :company_name, :title, :department, :address,
        :city, :latitude, :longitude, :postal_code, :state
      )
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @user_search = UserSearch.new(user_search_params)
    @pagy, @users = pagy(@user_search.users.order(:id))
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_path(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @user.trash
        format.html { redirect_to users_path, notice: "User was successfully trashed." }
        format.turbo_stream
        format.json { head :no_content }
      else
        format.html { redirect_to users_path, alert: "User could not be trashed." }
        format.turbo_stream { redirect_to users_path, alert: "User could not be trashed." }
        format.json { head :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :maiden_name, :email, :age, :gender,
      :phone, :username, :password, :birth_date, :image, :blood_group,
      :height, :weight, :eye_color, :hair_color, :hair_type, :university,
      :domain, :mac_address, :ip, :ein, :ssn, :user_agent
    )
  end

  def user_search_params
    return {} unless params.include?(:user_search)

    params.require(:user_search).permit(:search_term, :from_age, :to_age, :gender)
  end
end

app/views/users/addresses/_address.html.erb
<%= turbo_frame_tag dom_id(address) do %>
  <div class="row">
    <div class="col">
      <% @address_class = Address %>
      <h2 class="h4 mb-4"><%= @address_class.model_name.human %></h2>

      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>

      <div class="row border-bottom mx-2 mb-3 pb-2">
        <div class="col-sm-4">
          <p class="mb-0"><%= @address_class.human_attribute_name(:address) %></p>
        </div>
        <div class="col-sm-8">
          <p class="text-muted mb-0"><%= @address.address %></p>
        </div>
      </div>

      <div class="row border-bottom mx-2 mb-3 pb-2">
        <div class="col-sm-4">
          <p class="mb-0"><%= @address_class.human_attribute_name(:city) %></p>
        </div>
        <div class="col-sm-8">
          <p class="text-muted mb-0"><%= @address.city %></p>
        </div>
      </div>

      <div class="row border-bottom mx-2 mb-3 pb-2">
        <div class="col-sm-4">
          <p class="mb-0"><%= @address_class.human_attribute_name(:state) %></p>
        </div>
        <div class="col-sm-8">
          <p class="text-muted mb-0"><%= @address.state %></p>
        </div>
      </div>

      <div class="row border-bottom mx-2 mb-3 pb-2">
        <div class="col-sm-4">
          <p class="mb-0"><%= @address_class.human_attribute_name(:postal_code) %></p>
        </div>
        <div class="col-sm-8">
          <p class="text-muted mb-0"><%= @address.postal_code %></p>
        </div>
      </div>

      <div class="row border-bottom mx-2 mb-3 pb-2">
        <div class="col-sm-4">
          <p class="mb-0"><%= @address_class.human_attribute_name(:latitude) %></p>
        </div>
        <div class="col-sm-8">
          <p class="text-muted mb-0"><%= @address.latitude %></p>
        </div>
      </div>

      <div class="row border-bottom mx-2 mb-3 pb-2">
        <div class="col-sm-4">
          <p class="mb-0"><%= @address_class.human_attribute_name(:longitude) %></p>
        </div>
        <div class="col-sm-8">
          <p class="text-muted mb-0"><%= @address.longitude %></p>
        </div>
      </div>

      <div class="row justify-content-end pr-5 pt-4">
        <div class="col-3">
          <div class="d-flex justify-content-end">
            <%= link_to "Edit", edit_user_address_path(address.user, address), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/addresses/_form.html.erb
<%= turbo_frame_tag dom_id(address) do %>
  <div class="row">
    <div class="col">
      <h2 class="h4 mb-4"><%= address.class.model_name.human %></h2>
      
      <% url = address.persisted? ? user_address_path(address.user, address) : user_addresses_path(address.user) %>
      <%= form_with(model: address, url: url) do |form| %>
        <% if address.errors.any? %>
          <div class="alert alert-danger error-alert">
            <p><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</p>

            <ul>
              <% address.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        
        <div class="row border-bottom mx-2 mb-3 pb-2">
          <div class="col-4">
            <%= form.label :address, class: "form-label mb-0" %>
          </div>
          <div class="col-8">
            <%= form.text_field :address, class: "form-control p-0 border-0" %>
          </div>
        </div>

        <div class="row border-bottom mx-2 mb-3 pb-2">
          <div class="col-4">
            <%= form.label :city, class: "form-label mb-0" %>
          </div>
          <div class="col-8">
            <%= form.text_field :city, class: "form-control p-0 border-0" %>
          </div>
        </div>

        <div class="row border-bottom mx-2 mb-3 pb-2">
          <div class="col-4">
            <%= form.label :state, class: "form-label mb-0" %>
          </div>
          <div class="col-8">
            <%= form.text_field :state, class: "form-control p-0 border-0" %>
          </div>
        </div>

        <div class="row border-bottom mx-2 mb-3 pb-2">
          <div class="col-4">
            <%= form.label :postal_code, class: "form-label mb-0" %>
          </div>
          <div class="col-8">
            <%= form.text_field :postal_code, class: "form-control p-0 border-0" %>
          </div>
        </div>

        <div class="row border-bottom mx-2 mb-3 pb-2">
          <div class="col-4">
            <%= form.label :latitude, class: "form-label mb-0" %>
          </div>
          <div class="col-8">
            <%= form.number_field :latitude, step: 0.0000001, class: "form-control p-0 border-0" %>
          </div>
        </div>

        <div class="row border-bottom mx-2 mb-3 pb-2">
          <div class="col-4">
            <%= form.label :longitude, class: "form-label mb-0" %>
          </div>
          <div class="col-8">
            <%= form.number_field :longitude, step: 0.0000001, class: "form-control p-0 border-0" %>
          </div>
        </div>

        <div class="row justify-content-end pr-5 pt-4">
          <div class="col-3">
            <div class="d-flex justify-content-end gap-4">
              <% if address.persisted? %>
                <%= link_to "Cancel", user_address_path(address.user, address), class: "btn btn-danger" %>
              <% end %>
              <%= form.submit class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/addresses/edit.html.erb
<article class="container-fluid content">
  <header class="row mb-5">
    <div class="col">
      <nav class="bg-light rounded p-3 mb-1">
        <%= link_to user_address_path(@user, @address), class: "btn btn-light btn-lg" do %>
          <i class="bi bi-arrow-left"></i>
          <span>Back</span>
        <% end %>
      </nav>
    </div>
  </header>

  <div class="row justify-content-center">
    <div class="col">
      <div class="container px-0">
        <div class="row">
          <div class="col">
            <div class="card mb-4">
              <div class="card-body text-center user-card-body">
                
                <div class="row align-items-start">
                  <div class="col-4">
                    <% cache [@user, :profile] do %>
                      <%= render "users/user_profile", user: @user %>
                    <% end %>
                    
                    <%= render partial: "users/shared/vertical_navbar",
                          locals: { user: @user } %>
                  </div>
                  <div class="col-8 mt-4">
                    <%= render "form", address: @address %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</article>

app/views/users/addresses/new.html.erb
<article class="container-fluid content">
  <header class="row mb-5">
    <div class="col">
      <nav class="bg-light rounded p-3 mb-1">
        <%= link_to :back, class: "btn btn-light btn-lg" do %>
          <i class="bi bi-arrow-left"></i>
          <span>Back</span>
        <% end %>
      </nav>
    </div>
  </header>

  <div class="row justify-content-center">
    <div class="col">
      <div class="container px-0">
        <div class="row">
          <div class="col">
            <div class="card mb-4">
              <div class="card-body text-center user-card-body">
                
                <div class="row align-items-start">
                  <div class="col-4">
                    <% cache [@user, :profile] do %>
                      <%= render "users/user_profile", user: @user %>
                    <% end %>
                    
                    <%= render partial: "users/shared/vertical_navbar",
                          locals: { user: @user } %>
                  </div>
                  <div class="col-8 mt-4">
                    <%= render "form", address: @address %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</article>

app/views/users/addresses/show.html.erb
<article class="container-fluid content">
  <header class="row mb-5">
    <div class="col">
      <nav class="bg-light rounded py-3 px-5 mb-1 d-flex justify-content-between">
        <%= link_to users_path, class: "btn btn-light btn-lg" do %>
          <i class="bi bi-arrow-left"></i>
          <span>Back to Users</span>
        <% end %>

        <%= button_to @user, method: :delete,  data: { turbo: false },class: "btn btn-danger btn-rounded btn-lg" do %>
          <i class="bi bi-trash3-fill"></i>
          <span>Delete</span>
        <% end %>
      </nav>
    </div>
  </header>

  <div class="row justify-content-center">
    <div class="col">
      <div class="container px-0">
        <div class="row">
          <div class="col">
            <div class="card mb-4">
              <div class="card-body text-center user-card-body">
                
                <div class="row align-items-start">
                  <div class="col-4">
                    <% cache [@user, :profile] do %>
                      <%= render "users/user_profile", user: @user %>
                    <% end %>
                    
                    <%= render partial: "users/shared/vertical_navbar",
                          locals: { user: @user } %>
                  </div>
                  <div class="col-8 mt-4">
                    <% cache [@address, notice.present?] do %>
                      <%= render @address %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</article>